const items = [
  {
    id: "1",
    question_set: "Which is your favorite app?",
    question2_live: "Which is your favorite app?",
    options: ["Facebook", "Instagram", "YouTube", "Tinder"],
    images: ["q1_1.jpg", "q1_2.jpg", "q1_3.jpg", "q1_4.jpg"],
  },
  {
    id: "2",
    question_set: "What matters most in your life?",
    question2_live: "What matters most in your life?",
    options: ["Friendship", "Money", "Health", "Family"],
    images: ["q3_1.jpg", "q3_2.jpg", "q3_3.jpg", "q3_4.jpg"],
  },
  {
    id: "3",
    question_set: "What do you most enjoy doing in your spare time?",
    question2_live: "What do you most enjoy doing in your spare time?",
    options: ["Going to the gym", "Sleeping", "Watching TV", "Reading books"],
    images: ["q10_1.jpg", "q10_2.jpg", "q10_3.jpg", "q10_4.jpg"],
  },
  {
    id: "4",
    question_set: "Which superpower would you want to have?",
    question2_live: "Which superpower would you want to have?",
    options: ["Super strength", "Flying", "Invisibility", "Immortality"],
    images: ["q11_1.jpg", "q11_2.jpg", "q11_3.jpg", "q11_4.jpg"],
  },
  {
    id: "5",
    question_set: "What type of movies do you like the most?",
    question2_live: "What type of movies do you like the most?",
    options: ["Romance", "Horror", "Fantasy", "Comedy"],
    images: ["q16_1.jpg", "q16_2.jpg", "q16_3.jpg", "q16_4.jpg"],
  },
  {
    id: "6",
    question_set: "What's your favorite school subject?",
    question2_live: "What's your favorite school subject?",
    options: ["Maths", "History", "Music", "Physical education"],
    images: ["q14_1.jpg", "q14_2.jpg", "q14_3.jpg", "q14_4.jpg"],
  },
  {
    id: "7",
    question_set: "What is your favorite dessert?",
    question2_live: "What is your favorite dessert?",
    options: ["Cupcakes", "Pie", "Doughnuts", "Cookies"],
    images: ["q22_1.jpg", "q22_2.jpg", "q22_3.jpg", "q22_4.jpg"],
  },
  {
    id: "8",
    question_set: "If you win the lottery, what will you buy?",
    question2_live: "If you win the lottery, what will you buy?",
    options: ["Mansion", "Fast car", "Designer clothes", "Private plane"],
    images: ["q23_1.jpg", "q23_2.jpg", "q23_3.jpg", "q23_4.jpg"],
  },
  {
    id: "9",
    question_set: "Which of these describes your character best?",
    question2_live: "Which of these describes your character best?",
    options: ["Kind", "Funny", "Serious", "Angry"],
    images: ["q25_1.jpg", "q25_2.jpg", "q25_3.jpg", "q25_4.jpg"],
  },
  {
    id: "10",
    question_set: "What would you take to a desert island?",
    question2_live: "What would you take to a desert island?",
    options: ["Phone", "Knife", "Sunscreen", "Flashlight"],
    images: ["q27_1.jpg", "q27_2.jpg", "q27_3.jpg", "q27_4.jpg"],
  },
  {
    id: "11",
    question_set: "What kind of weather do you prefer?",
    question2_live: "What kind of weather do you prefer?",
    options: ["Hot", "Rainy", "Moderate", "Snowy"],
    images: ["q33_1.jpg", "q33_2.jpg", "q33_3.jpg", "q33_4.jpg"],
  },
  {
    id: "12",
    question_set: "What's your favorite emoji?",
    question2_live: "What's your favorite emoji?",
    options: ["Tears of Joy", "Heart-Eyes", "Smile", "Heart"],
    images: ["q35_1.jpg", "q35_2.jpg", "q35_3.jpg", "q35_4.jpg"],
  },
  {
    id: "13",
    question_set: "During which season is your birthday?",
    question2_live: "During which season is your birthday??",
    options: ["Winter", "Spring", "Summer", "Autumn"],
    images: ["q41_1.jpg", "q41_2.jpg", "q41_3.jpg", "q41_4.jpg"],
  },
  {
    id: "14",
    question_set: "What's your favorite place in nature?",
    question2_live: "What's your favorite place in nature?",
    options: ["Mountains", "Lake", "River", "Forest"],
    images: ["q37_1.jpg", "q37_2.jpg", "q37_3.jpg", "q37_4.jpg"],
  },
  {
    id: "15",
    question_set: "What's your favorite part of the day?",
    question2_live: "What's your favorite part of the day?",
    options: ["Morning", "Afternoon", "Evening", "Night"],
    images: ["q50_1.jpg", "q50_2.jpg", "q50_3.jpg", "q50_4.jpg"],
  },
];

export default items;
